farquhar:
  DELTA_CONVERGENCE: 1.0e-06
  NSC_Retroinhibition: false
  SurfacicProteins: false
CN:
  roots:
    K_AMINO_ACIDS_EXPORT: 0.00075
    K_NITRATE_EXPORT: 2.4999999999999998e-05
start_time: 960
stop_time: 2135
