senescence:
  SENESCENCE_MAX_RATE:
    blade: 9.0e-10
    stem: 4.0e-10
farquhar:
  DELTA_CONVERGENCE: 1.0e-06
  NSC_Retroinhibition: false
  SurfacicProteins: false
CN:
  PhotosyntheticOrgan:
    SIGMA_AMINO_ACIDS: 1.0e-08
    SIGMA_SUCROSE: 0.001
    VMAX_SUCROSE: 12
  grains:
    FILLING_END: 5076000
    FILLING_INIT: 1296000
    VMAX_STARCH: 10
  roots:
    K_AMINO_ACIDS_EXPORT: 2.5e-05
    K_NITRATE_EXPORT: 1.0e-07
start_time: 960
stop_time: 2135
